### ISSUE TITLE
Create an example page

### ISSUE THREAD

**Issue by bhagyas** [mreq/slick-lightbox#1]
To demonstrate the features.

**Comment by EnMod** [comment]
Is there any way to incorporate the functionality of the lightbox on items already in a Slick Gallery?  Or would a standalone jQuery lightbox be more effective?

**Comment by mreq** [comment]
See http://plnkr.co/IOpCRKjBJFX0Jp8G2I5w. I've added the `src` option which make this possible.

**Comment by mreq** [comment]
I've created a brand new demo page at http://mreq.github.io/slick-lightbox/demo/.
