### ISSUE TITLE
Bug: ie9 transition duration is undefined

### ISSUE THREAD

**Issue by marissajmc** [mreq/slick-lightbox#10]
slick-lightbox: v0.1.12
browser: ie9

Hello,
Line 263 is throwing an error in ie9 -
```
return this.transitionDuration = duration.indexOf('ms') > -1 ? parseFloat(duration) : parseFloat(duration) * 1000;
```

*Unable to get value of the property 'indexOf': object is null or undefined*

This is because duration is undefined at line 262. 
```
duration = this.modalElement.css('transition-duration');
```
I can fix this by explicitly setting a duration, but was wondering if there could be a better way? Whereabouts do you set the transition duration?
```
if (duration === undefined) {
    duration = '0.5s';
}
```

**Comment by mreq** [comment]
Nice catch, thanks! Fixed in v0.1.15.
