### ISSUE TITLE
Add video support

### ISSUE THREAD

**Issue by AntoineBoulanger** [mreq/slick-lightbox#11]
It would be nice to have youtube / vimeo embed support by adding the video url in the href attribute like this lightbox does: http://brutaldesign.github.io/swipebox/#video .

**Comment by mreq** [comment]
The plan is to stick with default slick functionality, as mentioned in https://github.com/mreq/slick-lightbox/issues/9. Once slack can do video embeds, I'll happily add lightbox support.

**Comment by amongiants** [comment]
@AntoineBoulanger In case you are still interested I added super basic video (iframe) support in fork

Fork: [https://github.com/amongiants/slick-lightbox](https://github.com/amongiants/slick-lightbox)
Usage: [http://amongiants.github.io/slick-lightbox/demo](http://amongiants.github.io/slick-lightbox/demo)

**Comment by dileepma** [comment]
@jongacnik swiping between youtube iframes not possible..any fix?

**Comment by jongacnik** [comment]
@dileepma That's a tricky fix. Maybe you could adjust code to use poster frames images and swap out the image with embed on tap? As mentioned the iframe support I added is super basic, just to get something running for a client project I was working on. I won't be actively working on that fork.

**Comment by mreq** [comment]
@dileepma You can overlay the iframe with a div and forward click events to the video?

**Comment by dileepma** [comment]
@mreq can you show me a sample fiddle?

**Comment by mreq** [comment]
Sorry but that's too much work. You can create an overlay using css and overriding the `createModalItems` function. Listen for click events and use the youtube js api.

**Comment by dileepma** [comment]
Can we stop video auto when we go to next slide?

**Comment by jongacnik** [comment]
@dileepma please look at the [demo](http://jongacnik.github.io/slick-lightbox/demo/). The **Video (more advanced)** demonstrates what you want to do. The fork only allows you to add iframes to slides, the rest of the implementation is up to you. Sorry I cannot help beyond that, best of luck.

**Comment by dileepma** [comment]
![image](https://cloud.githubusercontent.com/assets/17449787/17240662/72eb10ce-558a-11e6-9992-028962d8efb5.png)
 in Safari video alignment sucks (see the screen).. Better we can fix it..

**Comment by dileepma** [comment]
Found the solution. You need to add vendor prefixed style to recognize `transform` property in Safari. Add `-webkit-transform:translateY(-50%)` to `.slick-lightbox-slick-iframe-wrap` class.

**Comment by Coop920** [comment]
Thanks for putting the work into this functionality.  This was exactly what I needed for my site!

**Comment by shivanit2** [comment]
How can I access the slick afterChange and beforeChange event in this forked version of lightbox?

**Comment by raihanalatheef** [comment]
I have created a quick workaround for one of my project. You can work on the CSS though :)  https://codepen.io/raihanath/pen/raxzGdX
