### ISSUE TITLE
Consider wrapping the plugin with jQuery closure

### ISSUE THREAD

**Issue by gausarts** [mreq/slick-lightbox#12]
I got the errors:
```javascript
Uncaught TypeError: Cannot read property 'fn' of undefined
TypeError: $ is undefined in jquery
```

Till I wrapped the plugin with the regular closure: 
```javascript
(function($) {

})(jQuery);
```

I wonder if you could consider wrapping it that way in the next release?
Thanks.

**Comment by mreq** [comment]
Definitely should've done that. Added in v0.1.17.
