### ISSUE TITLE
Incompatible with slick 1.5.9 in Safari?

### ISSUE THREAD

**Issue by UnbekanntesPferd** [mreq/slick-lightbox#14]
The slick lightbox seems to be buggy when using with current slick.js (1.5.9) in Safari/iOS.
In all our test cases we couldn't swipe within the lightbox until the first element/image has been changed via prev/next-buttons.
The DOM changes on swipe, but still the first element is visible.

**Comment by gitsilvan** [comment]
I also have an issue with Safari - when using "fade: true" the lightbox becomes absolutely unusable (= lagging). When not using the fade animation everything is alright.

**Comment by gitsilvan** [comment]
I have problems as well - slick-lightbox is sadly not usable at all with slick versions newer than 1.5.5 and lots of slides in Safari.

**Comment by mreq** [comment]
As of now, it's not compatible with 1.5.9 in Safari.

Slick introduced the `useTransform` option, which is [buggy. See related issue](https://github.com/kenwheeler/slick/issues/1998).
