### ISSUE TITLE
seems rtl support missing

### ISSUE THREAD

**Issue by color2life** [mreq/slick-lightbox#15]
will porvide details shortly

**Comment by mreq** [comment]
That's indeed the case. Never needed to support rtl, but feel free to throw a pull request at me :)

**Comment by color2life** [comment]
Sure man I will

**Comment by mreq** [comment]
:+1:

**Comment by mreq** [comment]
feel free to reopen with a PR

**Comment by davsev** [comment]
What about slick lightbox rtl support?
Something new?
Searched the documentation couldnt find it...

**Comment by mreq** [comment]
#61
