### ISSUE TITLE
URL was changes after open the lightbox 

### ISSUE THREAD

**Issue by Gitsko** [mreq/slick-lightbox#16]
Hi,

i found a "bug?" on my Projekt. When i open a image the URL in Chrome and IE the url was changed.
The url was changed to the base url without any sub-pages.

In Firefox there are no Problem, it also works on Version 0.1.18.

I uses the slickslider and init so:
  $('#slick-demo').slick();
  $('#slick-demo').slickLightbox({
    src: 'src',
    itemSelector: '.item img'
  });

**Comment by mreq** [comment]
Hey, are you running a single page app?

**Comment by Gitsko** [comment]
sorry its run on a local typo3-site.

**Comment by mreq** [comment]
Use an arbitrary web server, don't run it as `file://`.

**Comment by mreq** [comment]
If you seriously do need to run it like that, use the `v0.1.18` version.
