### ISSUE TITLE
Existing slick getting too many slides

### ISSUE THREAD

**Issue by CHEWX** [mreq/slick-lightbox#18]
Hi,

When using the demo "Existing Slick", it's actually getting 2 too many slides as it's getting the cloned ones too. So when you slide through there are duplicates.

This gets even more problematic when showing more than one slide as it clones even more.

Thanks,
Tom

**Comment by mreq** [comment]
thanks for the catch :+1:

**Comment by dileepma** [comment]
I think this issue related to this
https://github.com/mreq/slick-lightbox/issues/22
