### ISSUE TITLE
Custom UI

### ISSUE THREAD

**Issue by CHEWX** [mreq/slick-lightbox#19]
Hi,

It would be cool if we could add an `element` option to take an object. As I'd like a custom close button and there is no way to do this currently, unless I am mistaken.

So we could do.

`
$slideshow.slickLightbox({
    el: {
        close : '<button type="button" class="slick-lightbox-close"></button>'
    }
});
`

Then simply after checking if it's set:

`this.options.el.close`

Thanks,
Tom

**Comment by mreq** [comment]
That's a great idea. Will look into that.
