### ISSUE TITLE
apply slick lightbox to a group of images

### ISSUE THREAD

**Issue by dileepma** [mreq/slick-lightbox#21]
In my site there are multiple times i used slick lightbox..When i clicked on an image it will show the  image but when click next it will load all the images that i'm using in all slick sliders in the page..can't we group and show images? I initialized plugin using class. is that the problem?

**Comment by mreq** [comment]
That sounds like a problem with your code. Provide a minimal jsfiddle/codepen.

**Comment by dileepma** [comment]
http://codepen.io/anon/pen/kXEaWm?editors=1010

See this pen..I separated my slides in two sets(set 1 and set 2).. but when we see in lightbox all the images (set 1 and set 2) displaying together. i want to group those.(as set 1 and set 2)

**Comment by mreq** [comment]
You're right. I'll fix that. For now, use `.each` http://codepen.io/mreq/pen/EyExzk?editors=1010#anon-login

**Comment by dileepma** [comment]
This solution not work for the appended images..any fix?
