### ISSUE TITLE
I'm getting multiple lightbox windows when i click one image

### ISSUE THREAD

**Issue by dileepma** [mreq/slick-lightbox#22]
![image](https://cloud.githubusercontent.com/assets/17449787/17177028/fe081170-542c-11e6-8b76-327ac25c7ed7.png)
Why am i getting multiple lightboxes when i click one image. This happens in sometimes when i click on a image in slick slider carasoul.

**Comment by mreq** [comment]
You're probably binding the lightbox multiple times. This issue tracker is meant for issues only, unlike http://stackoverflow.com which I'd recommend to you.

**Comment by dileepma** [comment]
Ok thanks..That's mean it is not a this plugin issue right?

**Comment by byNiko** [comment]
FWIW,
I had a similar situation with multiple backgrounds getting injected. 

I ended up needing to manually init the unopened lightbox and then manually close it:
		$('#my-element')[0].slickLightbox.init();
			$('#my-element')[0].slickLightbox.close();
