### ISSUE TITLE
Resizing in Safari with slick-lightbox open causes layout issues (sometimes)

### ISSUE THREAD

**Issue by davidklebanoff** [mreq/slick-lightbox#24]
Resizing in Safari with slick-lightbox open sometimes causes layout issues where the pictures are no longer center aligned and may be clipped by the browser.

Steps to reproduce:

1. Open Safari browser.
2. Navigate to a demo: [http://mreq.github.io/slick-lightbox/demo/](http://mreq.github.io/slick-lightbox/demo/)
3. Open a slick-lightbox.
4. Resize the window.
5. _Optional:_ Change slides using the keyboard's arrow keys. (Mousing over the slick-next and slick-prev buttons will actually cause the layout to be recalculated and fixes the issue)

The issue doesn't appear to occur in Chrome or Firefox.

![bug](https://cloud.githubusercontent.com/assets/7867074/17576557/e393de94-5f28-11e6-8639-d43f5096a7b6.jpg)

**Comment by mreq** [comment]
@davidklebanoff I could reproduce this by resizing the window and using arrow keys at the same time. Is that the issue, or is it more generic?

i.e. does it get stuck without changing slides at the same time? Couldn't reproduce that.

**Comment by davidklebanoff** [comment]
Hi @mreq , I'm no longer able to reproduce the issue.
