### ISSUE TITLE
Feature Request: Use they same slide index numbers as  an 'Existing Slick'

### ISSUE THREAD

**Issue by davidklebanoff** [mreq/slick-lightbox#25]
When attaching a slick-lightbox to an existing slick, it would be nice if the slides in the slick-lightbox had the same slide number as their corresponding slide in the original existing slick. Currently the slick-lightbox's slide numbers are generated such that the first slide is always `0` even if the user clicked on slide `3` to launch the slider.

Keeping the slide numbers in sync makes more advanced interactions between the two sliders much easier.

**Comment by mreq** [comment]
That's definitely a valid request. Will look into that, thanks.
