### ISSUE TITLE
Tons of dependencies ... are they all needed?

### ISSUE THREAD

**Issue by Bennethon** [mreq/slick-lightbox#27]
Adding slick-lightbox to my project made my npm production dependencies balloon up from about 10 to what looks like over 100? Is there any reason why this simple lightbox requires so many prouction dependencies ? Is it possible to clean that up?

**Comment by mreq** [comment]
All of the dependencies are inside of `devDependencies`, so they shouldn't be bothering you. Am not that familiar with npm world, feel free to submit a PR.

Existing `devDependencies` are need to build the project.

**Comment by Bennethon** [comment]
I see... they are all coming from the dependencies listed in the "shrinkwrap." I am not familiar with shrinkwrap...  but I'd be happy to take a look.

**Comment by mreq** [comment]
Feel free to reopen with more information.

**Comment by Bennethon** [comment]
I removed the shrinkwrap (deleted npm-shrinkwrap.json), did a production install, and the package seemed to work fine. The shrinkwrap file is forcing a lot of unnecessary dev dependencies to be installed during a production install. I recommend getting rid of it.
