### ISSUE TITLE
navigateByKeyboard not working

### ISSUE THREAD

**Issue by roby94** [mreq/slick-lightbox#29]
HI there,

I would like to switch images in the lightbox with keyboard (or even with some arrows if possible). I've set navigateByKeyboard: true, but it doesn't work, the image in the lightbox doesn't change, while the slick change slide.

How can i fix it?
Thank you

**Comment by mreq** [comment]
Provide a [jsfiddle](https://jsfiddle.net/) showing the issue and reopen. The [demo](http://mreq.github.io/slick-lightbox/demo/) is working.

**Comment by roby94** [comment]
Here is a pen with my code: [http://codepen.io/robyy94/pen/qaxJJX](url)

**Comment by mreq** [comment]
Yeah, that's not an issue in the plugin. You need to call the lightbox on the wrap. See http://codepen.io/mreq/pen/KgQAQa

**Comment by roby94** [comment]
Yes! My mistake!
Thank you very much!
