### ISSUE TITLE
Add events

### ISSUE THREAD

**Issue by yosefw** [mreq/slick-lightbox#3]
I need to call a function when the lightbox opens and another function when the lightbox closes.

Bootstrap has [several events for its modal](http://getbootstrap.com/javascript/#modals-events) plugin. I would love to have these for your plugin as well.

Thanks!

**Comment by mreq** [comment]
Great suggestion, thanks! I've added the basic set of events (aka the bootstrap ones).

**Comment by yosefw** [comment]
OMG! You're awesome! I'm putting this to use right away!

**Comment by mreq** [comment]
Cheers
