### ISSUE TITLE
Thumbnail preview/Sync scroll support?

### ISSUE THREAD

**Issue by codebymikey** [mreq/slick-lightbox#30]
Awesome library! As the title states, is it currently possible to achieve [Slider Syncing](http://kenwheeler.github.io/slick/)/Thumbnail preview functionality with the slick-lightbox?

If not, is it something that might be supported in the future?

Thanks.

**Comment by mreq** [comment]
Thanks for the kind words. I can definitely see adding a thumbnail preview to the bottom of the lightbox in the near future. Will actually tackle that once I get some time.

**Comment by codebymikey** [comment]
Thanks for the quick reply!, and keep up the good work dude.

I was dreading having to implement it myself if someone else already had! Oh well

Thanks again for your hard work.

**Comment by Justin-TheMitchells** [comment]
@codebymikey Did you ever figure out how to achieve this? I've been trying to get it going for a while and I'm having to give up on my current project and just make a lightbox with Slick from scratch.

**Comment by codebymikey** [comment]
@Justin-TheMitchells I think I ended up using [lightgallery](http://sachinchoolur.github.io/lightGallery/demos/index.html) instead.

Then I styled it accordingly.

**Comment by mreq** [comment]
@Justin-TheMitchells using a different plugin is def the way to go there :+1:

**Comment by mindeffects** [comment]
Na, don't go somewhere else! :-D

Maybe this is something for you:
```
<script>
$(document).ready(function(){
    $('.slider').slick({
        // your settings go here
    });
    $('.slider').slickLightbox({
        // your settings go here
    });
    
    // Let's sync these things
    $('.slider').slickLightbox().on({
        'show.slickLightbox': function(){ 
            $(".slick-lightbox .slick-prev").click(function() {
                $(".slider").slick('slickPrev');
            });
            $(".slick-lightbox .slick-next").click(function() {
                $(".slider").slick('slickNext');
            });
        }
  });
});
</script>
```
