### ISSUE TITLE
Add the library to CDNJS?

### ISSUE THREAD

**Issue by davidklebanoff** [mreq/slick-lightbox#32]
Add the library to CDNJS?
https://cdnjs.com/

**Comment by mreq** [comment]
Feel free to [send them a PR](https://github.com/cdnjs/cdnjs), should be faster. There's [almost 500](https://github.com/cdnjs/cdnjs/issues) open issues adding libraries, might take a while.

This is the "issue-muster" if you feel like it:

```
[Request] Add slick-lightbox


**Library name:** slick-lightbox
**Git repository url:** https://github.com/mreq/slick-lightbox
**npm package url(optional):** https://www.npmjs.com/package/slick-lightbox
**License(s):** MIT
**Official homepage:** http://mreq.github.io/slick-lightbox/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!
```

**Comment by davidklebanoff** [comment]
Ah, apparently a library must have "100 stars/watchers on GitHub" before being considered.

Hopefully one day!

**Comment by jonnymaboy** [comment]
there are just over 100 likers now.. does that mean it can get added ?

**Comment by mreq** [comment]
I don't know, never needed such a CDN. Feel free to send them a PR.

**Comment by jonnymaboy** [comment]
@davidklebanoff  are you still interested in getting this added to cdnjs ?

**Comment by davidklebanoff** [comment]
Not at the moment, no.
