### ISSUE TITLE
How to reduce margins in lightbox view?

### ISSUE THREAD

**Issue by jtlocsei** [mreq/slick-lightbox#33]
Love this lightbox. Very easy to set up and works beautifully. 

One question: how to make the image display bigger on the page?  The image has a max-height style set by javascript, and I would like to make it a larger % of the page height. 

![screenshot 2016-11-29 11 07 03](https://cloud.githubusercontent.com/assets/6704966/20707645/23170116-b624-11e6-831a-b9727a76ac27.png)

**Comment by mreq** [comment]
I'll release a new version with an option of setting the height %. In the meantime, you can use css transform to scale the image up a bit.

**Comment by jtlocsei** [comment]
Thanks! For the time being I actually edited the bit of javascript that sets max-height = 0.9*... and changed it to 1.0*... and that increased the image size somewhat while keeping it centered on the page.

**Comment by jtlocsei** [comment]
Thanks for the quick fix!
