### ISSUE TITLE
Applying slick methods to slickLightbox

### ISSUE THREAD

**Issue by Stegosource** [mreq/slick-lightbox#34]
Im trying to add some functionality so that if a slide is clicked, it will advance to the next slide. With the default slick instance, I can do this with something like: 

$('.slick-lightbox-slick-img').click(function() {
    $slideshow.slick('slickNext');
});

Is there a way to do that here? I guess Im just trying to access the slick object within the slickLightbox instance.

**Comment by mreq** [comment]
There is not, for now. I'll expose both the lightbox and the slick instances in the next version. Stay tuned.

**Comment by Stegosource** [comment]
Yeah, that would be awesome. Any idea on a timeline for that? Just curious. 

Another thing that would be nice would be a method to close the lightbox. We wanted to check if a user clicks the images, and advance the slider until the last slide. On the last slide, we close the lightbox.

**Comment by mreq** [comment]
Hopefully till the end of the week.

That will be solved by exposing the lightbox instance, as you will be able to call the appropriate method.

**Comment by mreq** [comment]
@Stegosource https://github.com/mreq/slick-lightbox#lightbox-instance

**Comment by Stegosource** [comment]
Yeah! That is badass. Awesome extension you have here. Good on you :)

**Comment by MartinDM** [comment]
This is also something I'm looking to do guys..

At present I have
`     $slider.on({
        'shown.slickLightbox': function () {
            console.log('shown');
        }
    }); `
However the lightbox event doesn't have access to slick.
How might I get access to the slick object (to access $slides) from some lightbox init method, not just once _within_ it and paging through (for which using a manual binding to the methods on slick?). Is there an equivalent for the lightbox init? 

Thanks @stegosource @mreq

**Comment by mreq** [comment]
@MartinDM `$slider[0].slickLightbox.slick` should work.

**Comment by mreq** [comment]
Oh, I've misread the question. If you want to initialize slick your way, pass a function as a `slick` option. See https://github.com/mreq/slick-lightbox/blob/master/src/scripts/slick-lightbox.coffee#L79
