### ISSUE TITLE
shouldOpen doesn't pass the actual event target to the callback

### ISSUE THREAD

**Issue by alexanderlperez** [mreq/slick-lightbox#35]
Items in the slick carousel might have controls added to them. It would be useful to pass the actual event object to the callback so that the `event.target` can be compared with the selector of a given control.

An example would be a slider with images having a "Remove this image" control and its respective event listener attached.  As it is, `shouldOpen` simply passes the slide itself, making it difficult to prevent both the lightbox being shown and the "Remove this image" event firing.

**Comment by alexanderlperez** [comment]
#36

**Comment by mreq** [comment]
thanks for the PR :+1:
