### ISSUE TITLE
Caption is cut off

### ISSUE THREAD

**Issue by timothyjensen** [mreq/slick-lightbox#37]
Firstly, thanks for the excellent work on this package.  My slideshow is working great except for the caption, which is being cut off at some screen sizes especially when it's a longer caption.  For example here https://cl.ly/2y3z0841172N, which can be seen live at https://btu.org/learning/manning-elementary-school/.  Can you recommend a way to prevent the captions from being cut off?

**Comment by mreq** [comment]
Thanks for the kind words. As the plugin is just a simple wrapper for slick, I've chosen not to consider such cases. Try setting `imageMaxHeight` to something lower than the `0.9` default.
