### ISSUE TITLE
Pagination Dot - Slick light box 

### ISSUE THREAD

**Issue by candyshien** [mreq/slick-lightbox#39]
Hi, would like to ask is there a pagination dot function for slider lightbox?

like slick has "Customize pagination"

**Comment by mreq** [comment]
There is currently not. You can change that by passing some `slick` options and adding some css.

**Comment by iamlinkus** [comment]
How would you go about passing slick options to a slick-lightbox object if you create an instance from an array of images and not html? Can't seem to catch slick slider instance...
