### ISSUE TITLE
Still working with new version?

### ISSUE THREAD

**Issue by ibsenleo** [mreq/slick-lightbox#4]
Says undefined in the image container

**Comment by mreq** [comment]
Working like it should, don't see undefined anywhere. Care to post a screenshot?

**Comment by ibsenleo** [comment]
Sorry, i solve it as i could.

i had to change line 51:
`return "<div class=\"slick-lightbox-slick-item\"><div class=\"slick-lightbox-slick-item-inner\"><img class=\"slick-lightbox-slick-img\" src=\"" + el.href + "\" />" + caption + "</div></div>";`

for this:
`return "<div class=\"slick-lightbox-slick-item\"><div class=\"slick-lightbox-slick-item-inner\"><img class=\"slick-lightbox-slick-img\" src=\"" + el.src + "\" />" + caption + "</div></div>";`

otherwise, the href property returns undefined for me.
Thanks for your answer and sorry for change your code for my porpouse.

Grettings 
Ibsen.

**Comment by mreq** [comment]
Sounds like you have a different HTML structure than what's proposed in the [readme](https://github.com/mreq/slick-lightbox#usage). For that, you do have to change the javascript code.

Closing this for now as that's neither an issue nor a constructive idea.
