### ISSUE TITLE
Captions are not loading

### ISSUE THREAD

**Issue by AlexanderBMAS** [mreq/slick-lightbox#46]
Captions are not loading using the data-caption option - this can be seen in the demo in repo as it is also not working.

**Comment by johnbburg** [comment]
If you are looking at the demo preview code, there seems to be an error there. There is no comma after:

```
caption: 'caption'
```

But it is in the source. So I'm not sue why it doesn't actually appear in the running demo.

**Comment by meetWibe** [comment]
Cations not working still, am i missing something?
https://codepen.io/meetwibe/pen/MogNYm

**Comment by AntoineBoulanger** [comment]
@meetWibe  It isn't. My PR https://github.com/mreq/slick-lightbox/pull/50 should fix it

**Comment by mreq** [comment]
Sorry about that, it was introduced by a PR. Am working on unit tests which will eliminate such cases. Fixed in 0.2.10.
