### ISSUE TITLE
Using "images" param with only one image not loading slick properly

### ISSUE THREAD

**Issue by ndimatteo** [mreq/slick-lightbox#47]
I'm using the `images` param to open a collection of images. It appears that if there is only one image in the array (ie: `['/img/example-1.jpg']` that slick does not initialize properly.

It should be able to still open the lightbox, if only one image is present.

**Comment by mreq** [comment]
Thanks for reporting. Am currently working on implementing qunit tests, which should make fixing bugs much easier. In the meantime, try downgrading as that might fix the issue.

**Comment by mreq** [comment]
This should be fine in master, see https://github.com/mreq/slick-lightbox/blob/master/test/tests/images.test.coffee#L12. Can you confirm?
