### ISSUE TITLE
How can I combine this with slider?

### ISSUE THREAD

**Issue by AizSedaj** [mreq/slick-lightbox#48]
Small images with sliding and bigger images on click with slider.

**Comment by mreq** [comment]
There's a [demo](http://mreq.github.io/slick-lightbox/demo/#slick) for exactly that.

**Comment by AizSedaj** [comment]
For those, who want to create a slider with thumbnails and a slider with big images, you should separately 
init .slick() for small slider and .slickLightbox() for fullscreen version.
