### ISSUE TITLE
Set defaults in triggering script

### ISSUE THREAD

**Issue by MetaBureau** [mreq/slick-lightbox#49]
Depending upon certain conditions, I wish to apply different settings via the script I use to trigger slick-lightbox.

I have tried applying the defaults in this script but without success.

What is the suggested method for moving defaults out of the main slick-lightbox.js file?

Here is how I imagined it to work...

$('.view-images ul').slickLightbox({
	background: 'rgba(255,0,255,1)',
    navigateByKeyboard: false,
    itemSelector: 'li img'
  });

**Comment by mreq** [comment]
That's exactly how you should do it. Not sure, what the question is. Feel free to reopen with more details.
