### ISSUE TITLE
Not really an issue but can this be added to a CDN like https://cdnjs.com ?

### ISSUE THREAD

**Issue by jonnymaboy** [mreq/slick-lightbox#51]

**Comment by mreq** [comment]
See #32

**Comment by jonnymaboy** [comment]
i have looked at the above but i dont really understand how to go about getting this added to cdn js.. ? Am i missing something.. why would you not want to get this added? if i knew how i would definitely do it. thanks

**Comment by mreq** [comment]
https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md
