### ISSUE TITLE
First image is only half height

### ISSUE THREAD

**Issue by stmalk** [mreq/slick-lightbox#53]
I have a php loop loading images into slick slider, so I added slick-lightbox to that gallery and it all works perfectly, but for some reason the very first image I click on to open in a lightbox is displayed only half or even third of its height. When I click on arrows back and forth, all other images load correctly. And if I go back to the first one it also becomes correct height. Only the first lick display is wrong. 

Also, if I click and drag on that image, kinda drag the cursor down, height changes to the full as needed. I don't know what kind of trickery is it.

What do you think it could be?

**Comment by mreq** [comment]
I have no idea :/ I'd be willing to help if you'd manage to put up a broken demo somewhere. Are you doing anything special with the plugin, or is it just a simple invocation?

**Comment by mreq** [comment]
Lack of response. Feel free to reopen.
