### ISSUE TITLE
Lightbox is not working while window resize, It happen in some cases

### ISSUE THREAD

**Issue by sibinx7** [mreq/slick-lightbox#6]
Lightbox work well in our Project. Very much thanks for this valuable plugin. We found some issues while changing window width and height ( It happen when we test responsiveness). Can you add some method to reinitialize while resizing window. I call my function in window resize event but it create more lightbox backgrounds and need to close each one...

Update : This happen when we give different breakpoints in slick

Can you please check this issue..

Thanks in advance

**Comment by mreq** [comment]
Can you provide a demo? Resizing works fine for me.

**Comment by sibinx7** [comment]
It will work in normal way. No issues with re sizing. But i have another situation, I have slick slider and sync slider (Slider Syncing). I have attached slick lightbox for this sync slider. In the slick configuration i have break points. It will work when we load or reload page..But window resizing is not worked with resizing..


This is a demo, I will delete this link soon...
http://portal.thinkautos.codingarena.in/vehicles/295-CADILLAC-STS-3-6-V6-SPORT-


You can re generate this

1. Add a slick slider with variable break points
2. Attach slick lightbox with it 
3. Resize your window


Sorry for bad English

**Comment by mreq** [comment]
Closing this as it seems to be an installation-specific problem. Try stackoverflow.com or similiar for support.
