### ISSUE TITLE
Slick-lightbox not working in rtl direction

### ISSUE THREAD

**Issue by Haseeb717** [mreq/slick-lightbox#60]
Using slick-direction which works fine in `ltr` but in Arabic locale my direction is `rlt` in which slick-lightbox is blank and not showing anything.

I search and find solution for slick in `rtl` cases but not find any solution for `slick-lightbox.`

**Comment by mreq** [comment]
Hey, `rtl` is not supported. I have no experience with it. However, a PR would be welcomed.

**Comment by Haseeb717** [comment]
Hi I fix that and want to push my change.

**Comment by mreq** [comment]
Great, make a pull request :+1:

**Comment by Haseeb717** [comment]
I cant able to push due to no access
