### ISSUE TITLE
Lightbox with previewimages (as for nav)

### ISSUE THREAD

**Issue by dgorges** [mreq/slick-lightbox#62]
Hi I like the idea creating a lightbox with with the slick slider. But what I am missing are thumbnail in the lightbox for the slider. Maybe this can be added, when I click an image that a copy of the slider in the lighbox is created as an as for nav slider with the thumbnailimages.

**Comment by mreq** [comment]
Hey. I don't plan to implement such a thing, as the plugin is meant as a single slick-wrapper.
