### ISSUE TITLE
Query - Another slick control within lightbox

### ISSUE THREAD

**Issue by ashishmundrajll** [mreq/slick-lightbox#65]
Hi All, Thanks for developing such a awesome control. We want to insert a slick with thumbnails (lets say with slidesToshow as 4 and asNavFor lightbox slick) inside the lightbox such that users can click on thumbnails within lightbox to navigate the lightbox main slick control. Something like http://frescojs.com/ Photos - © Dorhout Mees example.

Is that possible? If yes, is there an example code to achieve the same?

Many thanks,
Ashish

**Comment by mreq** [comment]
You'd have to create a custom solution #62
