### ISSUE TITLE
Not an isssue but how have you done that slick font thing on the close box?

### ISSUE THREAD

**Issue by cretace** [mreq/slick-lightbox#67]
Not an isssue, but how have you done that slick font thing on the close box?
I'm curious - I've skimmed the JS and can't see anything - all I see is that odd flattened 'x' character.
And where is a font called 'slick' loaded?

Nice plug-in- thanks!

**Comment by mreq** [comment]
Hey, the font is loaded with slick. As for the icon - https://github.com/mreq/slick-lightbox/blob/master/src/styles/slick-lightbox.sass#L102
