### ISSUE TITLE
Lightbox Modal and content loading twice when opened

### ISSUE THREAD

**Issue by Craig-Ninja** [mreq/slick-lightbox#68]
Hi There,

Ran into this issue recently where a Lightbox is opening twice (stacked on top of one another) they work perfectly fine, but when closing the top instance, I then also need to close the instance beneath it. Is this a known issue or should I provide some code so we can do some debugging?

Let me know.

**Comment by mreq** [comment]
Hey, that's not a known issue. You're most likely initializing the lightbox twice. Check that you're not loading your javascripts twice, that's a common issue.

**Comment by Craig-Ninja** [comment]
Thanks Mreq,

That was the exact issue, thanks for steering me in the right direction.
