### ISSUE TITLE
Button opens lightbox: this.options.lazy issue

### ISSUE THREAD

**Issue by ishetnogferre** [mreq/slick-lightbox#74]
**EDIT: I was using the npm package, which is version 0.2.10, so switched to the cdn one version 0.2.12, that fixed the problem.** 

Hi,

When I wanna use just a button that opens a set of images into a lightbox, I'm getting the following console error: "Cannot read property 'options' of undefined". Traced it back to the following code in the plugin:

<img width="621" alt="screen shot 2018-09-14 at 16 52 32" src="https://user-images.githubusercontent.com/6649706/45559423-b7743a00-b842-11e8-9588-1948f299cb7f.png">

It seems the 'this.options.lazy' isn't defined here, or am I forgetting an options field somewhere?
(If I replace the 'this.options.lazy' here, it all works)

Javascript behind the button(s):
```
<script>
    $('.photo-album').each(function(){
        var self = $(this);
        $(this).slickLightbox({
            images: self.data('images'),
        });
    });
</script>
```

**Comment by mreq** [comment]
Ye, that was fixed in [0.2.11](https://github.com/mreq/slick-lightbox/blob/master/CHANGELOG.md#0211---2017-10-10).
