### ISSUE TITLE
Excluding elements inside slide from opening lighbox

### ISSUE THREAD

**Issue by atempel** [mreq/slick-lightbox#75]
I'm using buttons inside each Slick slide, that have different functionalities. One of them opens the lightbox, the other two: One downloads the image, and the other Scrolls to another page element.

After implementing the buttons inside each slide (they are simply "a" selectors with styling), I found that all the buttons were opening the lightbox, and not performing its intended functionality.
I thought "shouldOpen" to be the option for this to work, so I implemented in the given way:
```
$('.gallery-class').slickLightbox({
  src: 'data-image',
  itemSelector: '.gallery-item-class',
  shouldOpen: function($instance, $clickedElement, $clickEvent) {
    if($clickedElement == $('.element-action-class a.action')) {
      console.log('Don't Open - Action');
      return false;
    } else {
      return true;
    }
  }
```
I'm sorry if I missed something, but this implementation didn't do anything, and I'm kinda lost since there's no information regarding the usage of this option further than what's in the README. 

> Given a function, checks the return value before opening. If the function returns a falsy value, the lightbox is not opened upon clicking on the items. Accepts three arguments - the slick lightbox instance as the first, the clicked element as the second and the click event as the last.

I thought I've built the function exactly how the description said, but apparently missed something, any help?

**Comment by atempel** [comment]
Disregard... Yeah, I missed something.
Found the demo page, which shows a way to use it. I was right on.
http://mreq.github.io/slick-lightbox/demo/#prevent-opening

At the same time, the problem seems to have changed.
This option just gives the Slick Item clicked, not the exact element clicked.

Well, since it's kind of out of `slick-lightbox` scope, that's it, I'll look for a solution. haha

**Comment by mreq** [comment]
Works  fine for me https://jsfiddle.net/mreq/23Luga7x/5/

**Comment by atempel** [comment]
> Works fine for me https://jsfiddle.net/mreq/23Luga7x/5/

Yeah! It works, I figured out with the demo, but any link you put inside Slick will trigger the lightbox, and if that link have any other functionality other than open the lightbox, it won't work.

Based on the fiddle you made: https://jsfiddle.net/23Luga7x/10/

**Comment by mreq** [comment]
`shouldOpen` works exactly like it's intended to - what you're looking for, is probably a different `itemSelector` - https://jsfiddle.net/mreq/23Luga7x/12/

**Comment by atempel** [comment]
@mreq Sorry for the confusion, you are completely right. I found a way around with exactly that you just said. Worked like a charm. My problem was my slide structure, I'd put the buttons inside the `itemSelector`, so every click on the buttons (which triggered the `itemSelector` opened the lightbox). My solution was simply move the item selector for one of the buttons.
Thanks again for the help! This issue is solved :D
