### ISSUE TITLE
Include /src in Bower package

### ISSUE THREAD

**Issue by yosefw** [mreq/slick-lightbox#8]
I would love to keep the plugin updated and maintained through bower, but I'm relying on the source less file that isn't included. Please consider changing this.

**Comment by mreq** [comment]
Sorry for not replying, am finishing my uni degree and don't really have time to go through stuff. Will do so during June. As for including /src I'm definitely not against it.

Thanks for the pull request as well.

**Comment by yosefw** [comment]
@mreq Thanks! Good luck with your degree :smile:

**Comment by mreq** [comment]
Added.

**Comment by yosefw** [comment]
Thanks! :-)
