### ISSUE TITLE
Use lightbox without slick

### ISSUE THREAD

**Issue by garygreen** [mreq/slick-lightbox#9]
Really weird question but I wonder if this plugin can be used to create a lightbox, without any slick stuff in it? Like just regular HTML....

Reason I ask is because I'm currently using slickjs and and another lightbox plugin and it doesn't make sense to include two lightbox-capable plugins. Would be cool to not have to use the other lightbox plugin at all and just use this.

Or...maybe split out the lightbox stuff into a seperate package? What do you think?

**Comment by mreq** [comment]
Not really sure if I understand you well -  since you're using slick anyways, you might just use the default settings?

If you don't want to use slick for the sliding, try passing your own `initSlick` function, as mentioned in the docs. You might also want turn `navigateByKeyboard` off, as it assumes slick.

**Comment by mreq** [comment]
See https://github.com/mreq/slick-lightbox/blob/master/src/scripts/slick-lightbox.coffee#L62

**Comment by garygreen** [comment]
Hmm let me try and explain a different way...

To me there is two parts to how this plugin works: 1. The lightbox side and 2. Putting stuff in the lightbox (i.e. a slickjs instance).

I would like to use this plugin for not only it's purpose (putting a slick slider in the lightbox) but also use it as a generic lightbox where I can put anything I like in it. For example (in an ideal world):

```javascript
$.slickLightbox.open({
	html: '<p>My custom stuff in the lightbox</p>'
});
```

I know it's a bit of a weird thing because it's purpose is mainly for slickjs, but I think it would be good to make it more modular you could do something like that. That way I don't have to include another jquery plugin just for lightbox stuff... because I can use this. If this makes sense?

**Comment by mreq** [comment]
You can mimic the lightbox-side quite easily (using the same markup) + hooking some basic [events](https://github.com/mreq/slick-lightbox/blob/master/src/scripts/slick-lightbox.coffee#L85). I don't feel like supporting non-gallery lightboxes, as that would make the plugin quite complex and big (gathering more and more features, settings and code). As the name suggest, this plugin is ment to be a simple wrapper for the slick carousel.

Closing this, but feel free to discuss.

**Comment by garygreen** [comment]
I disagree it would make it more complex as it would be more of a shift in refactoring the code to make it easier to use the lightbox component only. Anyway thanks for the suggestions
